### ISSUE TITLE
How to use the results samples! 

### ISSUE THREAD

**Issue by ggous** [ajz34/Kennard-Stone-Efficient#1]
Hello and thanks for the library!

I wanted to ask you how can I use the results...

For example, I have this code:

```
import numpy as np
from KS_Sampling_Python import ks_sampling

X = np.random.randint(100, size=(4, 4))

ks_result = ks_sampling(X, n_result=10)
```

which gives me:
```
X = array([[45, 72, 63, 44],
       [50, 45, 69,  1],
       [49, 82, 68, 84],
       [83, 11, 65, 16]])
```

```
ks_result
(array([2, 3, 1, 0, 0, 0, 0, 0, 0, 0]),
 array([104.06728593,  49.85980345,  41.72529209, 104.06728593,
        104.06728593, 104.06728593, 104.06728593, 104.06728593,
        104.06728593,   0.        ]))

```

Questions:

1) So, I have a 16 elements array (X) and I have `ks_result[0]` containing: `(array([2, 3, 1, 0, 0, 0, 0, 0, 0, 0])`

What it means? What kind of sample are that?

Normally, if you return the indices of the samples, I could do:
`X_new = X[X[ks_result[0], :]]`

Now, how an I select the computed samples from the initial `X`?

2) If I use : 
`ks_result = ks_sampling(X, n_result=100)` , so `n_result` is bigger than the size of the initial array `X`, 
the code still runs and returns for example:

```
ks_result[0].shape
(100,)
```
Shouldn't have been a check for this?

Thanks!

----- UPDATE  ----- 
3) Another example.

Is this example right? 

```
import pandas as pd
from KS_Sampling_Python import ks_sampling

df = pd.DataFrame({'a':[1,2,3,43,54,55,5,5,6,6,4,6,7,7],
                   'b':[4,5,6,2,3,344,4,54,5,6,67,3,37,1],
                   'c':[7,8,9,34,4,55,5,5,6,7,7,7,8,88]})


features = df.drop('c', axis=1)
labels = df['c']

ks_result = ks_sampling(features.values, n_result=5)

print(features.shape)
print(labels.shape)

features_new = features[features.index.isin(ks_result[0])]
labels_new = labels[labels.index.isin(ks_result[0])]

print(features_new.shape)
print(labels_new.shape)

```

If I use the "correct" above code to another dataframe that I am working on, I receive:

```
#select 80% of data
ks_result = ks_sampling_mem(features.values,
                                                 n_result=int(len(features.values) * 0.8))

features_data = features[features.index.isin(ks_result[0])]
labels_data = labels[labels.index.isin(ks_result[0])]


print(int(len(features.values) * 0.8))
print('Features before:', features.shape)
print('Features after:', features_data.shape)
print('Labels before:', labels.shape)
print('Labels after:', labels_data.shape)
```

Result:

```
34696
Features bedore: (43371, 78)
Features after: (5482, 78)
Labels bedore: (43371,)
Labels after: (5482,)
```

So, you can see that the shape I am receiving after applying ks_result is not the 80% of the initial shape but way less (I don't have nan values).

**Comment by ajz34** [comment]
Hi!

Apology that I'm not convenient to work for about 6 weeks.

For the questions mentioned,

## Questions 2

Your comments of Question 2 is correct. Python code does not have a check on this. Current python code does not raise error when `n_result > n_sample`, and this may be corrected later. Well, C code should have checked this problem, so using C backend will raise an assertion error. C backend should also also significantly faster.

## Question 1

For Question 1, I suggest the following example.
This example merely changes shape of `X` to (16, 4), i.e., this generates 16 samples, where each sample is a 4-element vector (`n_sample, n_feature = 16, 4`).
This example is valid, since number of samples `n_sample = 16` is not less than number of results user defined `n_result = 10`.

```python
import numpy as np
from KS_Sampling import ks_sampling

if __name__ == '__main__':
    np.random.seed(0)
    X = np.random.randint(100, size=(16, 4))
    ks_result = ks_sampling(X, n_result=10, backend="Python")
    print(ks_result)
```
This should give
```
(array([ 8, 13,  6,  1,  4, 15, 12,  3, 10,  7]), array([131.47623359,  96.75226096,  86.45808233,  72.64984515,
        62.65780079,  61.90315016,  43.97726685,  42.20189569,
        39.25557285,   0.        ]))
```

The first array is indexes sampled by Kennard-Stone algorithms, as you may have guessed. To retrive data of sampled data, the following code works:
```python
>>> print(X[ks_result[0], :])
[[82 99 88 49]
 [28 34  0  0]
 [72  9 20 80]
 [67  9 83 21]
 [39 87 46 88]
 [17 79  4 42]
 [23 35 75 55]
 [88 12 58 65]
 [39 32 65  9]
 [69 79 47 64]]
```

The second array is distance between sampled data. For example, the first and second distance (131.47623359, 96.75226096) is obtained by (euclid distance as default)
```python
>>> print(np.linalg.norm(X[8] - X[13]))
131.4762335937564
>>> print(np.linalg.norm(X[13] - X[6]))
96.75226095549395
```
Though length of this array is 10, only 9 distances are valid.

## Question 3

I guess that first block of code is correct.

For second block, I'm not sure what lets the code behaves incorrectly.

From my thoughts, I suggest to check whether some indexes of pandas dataframe shares the same value. Selecting indexes by `index.isin` works only when indexes are 0, 1, 2, ... but will not work when indexes are self-defined. Using `iloc` to select the sampled data is also a choice.

Following code shows a boundary example, that if index of dataframe is self-defined, then using `index.isin` to select sampled data could fail.

```python
import numpy as np
from KS_Sampling import ks_sampling_mem
import pandas as pd

if __name__ == '__main__':
    np.random.seed(1)
    df_noidx = pd.DataFrame({'a': np.random.randn(100),
                             'b': np.random.randn(100)})
    idx = pd.Index(np.random.randint(10, size=100))
    df_withidx = pd.DataFrame(df_noidx, index=idx)

    ks_result = ks_sampling_mem(df_noidx, n_result=80)
    print("index.isin()")
    print(df_noidx[df_noidx.index.isin(ks_result[0])].shape)
    print(df_withidx[df_withidx.index.isin(ks_result[0])].shape)
    # (80, 2)
    # (85, 2)
    print("iloc[]")
    print(df_noidx.iloc[ks_result[0]].shape)
    print(df_withidx.iloc[ks_result[0]].shape)
    # (80, 2)
    # (80, 2)
```

## Additional marks

I'm happy that if this code spinnet helps ~ Maybe there should be some additional documents :)
Also not that current code is not safe (index order may change) if distances of several data is too close (often occur for integer points, or extremely large dataset).

**Comment by ggous** [comment]
Hi, no problem!

Thanks for the answer!
Make sense now.
